api/urls.py
import imp
from django.urls import path,include
from api import views

app_name='api'

##defining the urls to work with

urlpatterns = [
    #path('members/',views.MemberList.as_view()),
    path('signup/',views.signupAppUser),
    path('login/',views.loginUser),
    
]

central_branch/urls.py
import imp
from django.urls import path,include
from . import views
from .views import GetTaskCategoryPointsAjax, SaveMemberTaskPointsAjax, UpdatePositionAjax,UpdateAwardAjax
from .views import UpdatePositionAjax,UpdateRestrictionAjax,AwardRanking

app_name='central_branch'

##defining the urls to work with

urlpatterns = [
    
    #central_homeage
    path('',views.central_home, name='central_home'),
    #teams page
    path('teams/',views.teams,name='teams'),
    #team details page
    path('team_details/<int:primary>/<str:name>',views.team_details,name='team_details'),
    #manage team Page
    path('manage_team/<str:pk>/<str:team_name>',views.manage_team,name="manage_team"),

    #PANEL
    path('panels',views.panel_home,name="panels"),
    #panel details
    path('panels/<int:panel_id>',views.branch_panel_details,name="panel_details"),
    path('panels/<int:panel_id>/officers',views.branch_panel_officers_tab,name="panel_details_officers"),
    path('panels/<int:panel_id>/volunteers',views.branch_panel_volunteers_tab,name="panel_details_volunteers"),
    path('panels/<int:panel_id>/alumni',views.branch_panel_alumni_tab,name="panel_details_alumni"),

    
    #for updating value in team member select box in event assigning
    # path('get_updated_options/', views.get_updated_options_for_event_dashboard, name='get_updated_options'),
    #others page
    path('others/',views.others,name="others"),
    
    
    #WEBSITE Management URL Path
    path('manage_website/homepage',views.manage_website_homepage,name="manage_website_home"),
    path('manage_website/homepage/update/<int:pk>',views.manage_website_homepage_top_banner_update,name="manage_website_home_top_banner_update"),
    # path('manage_website/homepage/volunteer_of_the_month/<int:pk>',views.update_volunteer_of_month,name="update_vom"),
    path('manage_website/achievements',views.manage_achievements,name="manage_achievements"),
    path('manage_website/achievements/update/<int:pk>',views.update_achievements,name="achievements_update"),
    path('manage_website/news',views.manage_news,name="manage_news"),
    path('manage_website/news/update/<int:pk>',views.update_news,name="update_news"),
    path('manage_website/blogs',views.manage_blogs,name="manage_blogs"),
    path('manage_website/blogs/update/<int:pk>',views.update_blogs,name="update_blogs"),
    path('manage_website/blogs/requests',views.blog_requests,name="blog_requests"),
    path('manage_website/blogs/requests/<int:pk>',views.publish_blog_request,name="publish_blog_requests"),
    path('manage_website/research',views.manage_research,name="manage_research"),
    path('manage_website/research/update/<int:pk>',views.update_researches,name="update_researches"),
    path('manage_website/research/requests',views.manage_research_request,name="manage_research_request"),
    path('manage_website/research/requests/<int:pk>',views.publish_research_request,name="publish_research_request"),
    path('manage_website/magazine',views.manage_magazines,name="manage_magazines"),
    path('manage_website/magazine/update/<int:pk>',views.update_magazine,name="update_magazine"),
    path('manage_website/gallery',views.manage_gallery,name="manage_gallery"),
    path('manage_website/gallery/update/image/<int:pk>',views.update_images,name="update_image"),
    path('manage_website/gallery/update/video/<int:pk>',views.update_videos,name="update_video"),
    path('manage_website/exemplary_members',views.manage_exemplary_members,name="manage_exemplary_members"),
    path('manage_website/exemplary_members/update/<int:pk>',views.update_exemplary_members,name="update_exemplary_members"),
    path('manage_website/about/ieee/',views.manage_about,name = "manage_about"),
    path('manage_website/about/ieee_region_10/',views.ieee_region_10,name = "ieee_region_10"),
    path('manage_website/about/ieee_bangladesh_section/',views.ieee_bangladesh_section,name = "ieee_bangladesh_section"),
    path('manage_website/about/ieee_nsu_student_branch/',views.ieee_nsu_student_branch,name = "ieee_nsu_student_branch"),
    path('manage_website/about/faq/',views.faq,name = "faq"),
    path('manage_website/toolkit',views.manage_toolkit,name="manage_toolkit"),
    path('manage_website/toolkit/update/<int:pk>',views.update_toolkit,name="update_toolkit"),
    path('manage_website/feedbacks',views.feedbacks,name="feedbacks"),
    path('manage_access',views.manage_view_access,name="manage_access"),
    
    #About Page preview urls
    path('manage_website/about/ieee/preview/',views.manage_about_preview,name = "manage_about_preview"),
    path('manage_website/about/ieee_region_10/preview/',views.ieee_region_10_preview,name = "ieee_region_10_preview"),
    path('manage_website/about/ieee_bangladesh_section/preview/',views.ieee_bangladesh_section_preview,name = "ieee_bangladesh_section_preview"),
    path('manage_website/about/ieee_nsu_student_branch/preview/',views.ieee_nsu_student_branch_preview,name = "ieee_nsu_student_branch_preview"),
    path('manage_website/about/faq/preview',views.faq_preview,name = "faq_preview"),

    #Events urls
    #Event control page 
    path('events/',views.event_control_homepage, name='event_control'),
    #Event Creation Form page 1
    path('events/create_event/',views.event_creation_form_page,name='event_creation_form1'),
    #Event Creation Form Page 2
    path("events/create_event/<int:event_id>/page-2/", views.event_creation_form_page2, name="event_creation_form2"),
    #Event creation page 3
    path("events/create_event/<int:event_id>/page-3/", views.event_creation_form_page3, name="event_creation_form3"),
    #Event edit page
    path('event_details/<int:event_id>/edit/',views.event_edit_form,name='event_edit_form'),
    #Event media tab page
    path('event_details/<int:event_id>/edit/media/',views.event_edit_media_form_tab,name='event_edit_media_form_tab'),
    #Event graphics tab page
    path('event_details/<int:event_id>/edit/graphics/',views.event_edit_graphics_form_tab,name='event_edit_graphics_form_tab'),
    #Event graphics links sub tab page
    path('event_details/<int:event_id>/edit/graphics/links/',views.event_edit_graphics_form_links_sub_tab,name='event_edit_graphics_form_links_sub_tab'),
    #Event content tab page
    path('event_details/<int:event_id>/edit/content/',views.event_edit_content_form_tab,name='event_edit_content_form_tab'),
    #Mega Event Creation Form
    path('events/create_mega_event/',views.mega_event_creation,name="mega_event_creation"), 
    #Mega Events homepage
    path('events/mega_events/',views.mega_events,name="mega_events"), 
    #Mega Events edit
    path('events/mega_event_edit/<int:mega_event_id>/',views.mega_event_edit,name="mega_event_edit"), 
    #Add Events to Mega Event
    path('events/mega_event_add_event/<int:mega_event_id>/',views.mega_event_add_event,name="mega_event_add_event"), 

    #Event preview
    path('event_details/<int:event_id>/preview/',views.event_preview,name='event_preview'),
    #Event Feedback
    path('event_details/<int:event_id>/feedbacks/',views.event_feedback,name="event_feedback"),  

    #Event Google Calendar
    path('event_details/<int:event_id>/google_calendar/',views.event_google_calendar,name="google_calendar"),  

    #Members list
    path('members/',views.insb_members_list,name="members_list"),
    #Members details list
    path('member_details/<int:ieee_id>',views.member_details,name="member_details"),

    # get dynamic data in JS position edit
    path('get_position_data/',UpdatePositionAjax.as_view(),name="update_position"),
    #evente excel generation url
    path('generateExcelSheet_events_by_year/<int:year>',views.generateExcelSheet_events_by_year,name="generateExcelSheet_events_by_year"),
    
    # volunteer awards
    path('volunteer_awards/panels/',views.volunteerAwardsPanel,name="volunteer_awards_panels"),
    path('volunteer_awards/panel/<int:panel_pk>/awards',views.panel_specific_volunteer_awards_page,name="panel_specific_volunteer_awards_page"),
    path('volunteer_awards/panel/<int:panel_pk>/awards/<int:award_pk>',views.panel_and_award_specific_page,name="panel_award_specific_volunteer_awards_page"),
    path('get_award_data/',UpdateAwardAjax.as_view(),name="update_award"),
    path('rank_award/',AwardRanking.as_view(),name="award_ranking"),
    #event excel generation url
    path('generateExcelSheet_events_by_year/<int:year>',views.generateExcelSheet_events_by_year,name="generateExcelSheet_events_by_year"),
    path('members/user_access/',views.user_access,name="user_access"),
    path('update_restricted_members/',UpdateRestrictionAjax.as_view(),name="update_restricted_members"),

    #task assignation urls
    path('create_task/',views.create_task,name="create_task"),
    path('task_home/',views.task_home,name="task_home"),
    path('task/<int:task_id>',views.task_edit,name="task_edit"),
    path('task/<int:task_id>/upload_task/',views.upload_task,name="upload_task"),
    path('task/<int:task_id>/forward_to_incharges/<int:team_primary>',views.forward_to_incharges,name="forward_to_incharges"),
    path('task/<int:task_id>/add_task/',views.add_task,name="add_task"),
    path('task/get_task_category_points',GetTaskCategoryPointsAjax.as_view(),name="get_task_category_points"),
    path('task/save_mem_task_points/<team_primary>/',SaveMemberTaskPointsAjax.as_view(),name="save_mem_task_points"),

    #task history
    path('task_history/individual/<int:ieee_id>',views.individual_task_history,name="individual_task_history"),
    path('task_history/team/<int:team_primary>',views.team_task_history,name="team_task_history"),
    ##
    path('task_leaderboard/',views.task_leaderboard,name="task_leaderboard"),

    #Email
    path('mail/',views.mail,name="mail"),
    path('mail/view/<str:mail_id>',views.view_mail,name="view_mail"),
    path('mail/send_mail_request/', views.SendMailAjax.as_view(),name='send_mail_request'),

chapters_and_affinity_group/urls.py
from django.urls import path
from . import views

app_name="chapters_and_affinity_group"

urlpatterns = [
    
    path('sc_ag_renewal_stats/',views.get_sc_ag_renewal_stats,name="sc_ag_renewal_stats"),
    path('<str:primary>/',views.sc_ag_homepage,name='sc_ag_homepage'),
    # For SC AG Members
    path('<str:primary>/members',views.sc_ag_members,name='sc_ag_members'),
    
    # For SC AG Panels
    path('<str:primary>/panels',views.sc_ag_panels,name="sc_ag_panels"),
    path('<str:primary>/panels/<str:panel_pk>',views.sc_ag_panel_details,name="sc_ag_panel_details"),
    path('<str:primary>/panels/<str:panel_pk>/officers',views.sc_ag_panel_details_officers_tab,name="sc_ag_panel_details_officers"),
    path('<str:primary>/panels/<str:panel_pk>/volunteers',views.sc_ag_panel_details_volunteers_tab,name="sc_ag_panel_details_volunteers"),
    path('<str:primary>/panels/<str:panel_pk>/alumni',views.sc_ag_panel_details_alumni_members_tab,name="sc_ag_panel_details_alumni"),
    
    # For SC AG Renewals
    path('<str:primary>/membership_renewal',views.sc_ag_membership_renewal_sessions,name="sc_ag_membership_renewal"),
    path('<str:primary>/membership_renewal/<str:renewal_session>/requests',views.sc_ag_renewal_session_details,name="sc_ag_membership_renewal_details"),
    path('<str:primary>/sc_ag_renewal_excel_sheet/<str:renewal_session>',views.sc_ag_renewal_excel_sheet,name="generate_sc_ag_renewal_excel"),
    
    # For SC AG Data Access
    path('<str:primary>/manage_access',views.sc_ag_manage_access,name="sc_ag_manage_access"),
    
    # for SC AG Events
    path('<str:primary>/events/',views.event_control_homepage,name="event_control_homepage"),
    path('<str:primary>/events/create_event/',views.event_creation_form_page,name='event_creation_form1'),
    path('<str:primary>/events/create_event/<int:event_id>/page-2', views.event_creation_form_page2, name="event_creation_form2"),
    path('<str:primary>/events/create_event/<int:event_id>/page-3', views.event_creation_form_page3, name="event_creation_form3"),
    path('<str:primary>/event_details/<int:event_id>/edit/',views.event_edit_form,name='event_edit_form'),
    #Event media tab page
    path('<str:primary>/event_details/<int:event_id>/edit/media',views.event_edit_media_form_tab,name='event_edit_media_form_tab'),
    #Event graphics tab page
    path('<str:primary>/event_details/<int:event_id>/edit/graphics',views.event_edit_graphics_form_tab,name='event_edit_graphics_form_tab'),
    #Event graphics links sub tab page
    path('<str:primary>/event_details/<int:event_id>/edit/graphics/links',views.event_edit_graphics_form_links_sub_tab,name='event_edit_graphics_form_links_sub_tab'),
    #Event content tab page
    path('<str:primary>/event_details/<int:event_id>/edit/content',views.event_edit_content_form_tab,name='event_edit_content_form_tab'),
    #Event preview
    path('<str:primary>/event_details/<int:event_id>/preview/',views.event_preview,name='event_preview'),
    #Event Feedback
    path('<str:primary>/event_details/<int:event_id>/feedbacks/',views.event_feedback,name='event_feedback'),
    #Manage Main Website
    path('<str:primary>/manage_main_website',views.manage_main_website,name="manage_main_website"),
    #Manage Main Website Preview
    path('<str:primary>/manage_main_website/preview',views.manage_main_website_preview,name="manage_main_website_preview"), 
    #Feed Back
    path('<str:primary>/feedbacks',views.feedbacks,name="feedbacks"),
    #Event Google Calendar
    path('<str:primary>/event_details/<int:event_id>/google_calendar/',views.event_google_calendar,name="google_calendar"),
    #Mega Event Creation Form
    path('<str:primary>/events/create_mega_event/',views.mega_event_creation,name="mega_event_creation"), 
    #Mega Events homepage
    path('<str:primary>/events/mega_events/',views.mega_events,name="mega_events"), 
    #Mega Events edit
    path('<str:primary>/events/mega_event_edit/<int:mega_event_id>/',views.mega_event_edit,name="mega_event_edit"), 
    #Add Events to Mega Event
    path('<str:primary>/events/mega_event_add_event/<int:mega_event_id>/',views.mega_event_add_event,name="mega_event_add_event"), 
    #excel generation
    path('<str:primary>/events/generateExcelSheet_events_by_year_sc_ag/<int:year>/',views.generateExcelSheet_events_by_year_sc_ag,name = "generateExcelSheet_events_by_year_sc_ag")
]

insb_port/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    
    path('',include('main_website.urls',namespace='main_website')),
    path('portal/',include('port.urls',namespace='port')),
    path('api/',include('api.urls')),
    path('admin/', admin.site.urls),
    path('system/',include('system_administration.urls',namespace="system")),
    path('portal/users/',include('users.urls',namespace="users")),
    path('portal/notifications/',include('notification.urls',namespace="notification")),
    path('portal/recruitment/',include('recruitment.urls',namespace="recruitment")),
    path('portal/central_branch/',include('central_branch.urls',namespace='central_branch')),
    path('portal/membership_development_team/',include('membership_development_team.urls',namespace='membership_development_team')),
    path('portal/public_relation_team/',include('public_relation_team.urls',namespace='public_relation_team')),
    path('portal/system_administration',include('system_administration.urls',namespace='system_administration')),
    path('portal/events_and_management_team/',include('events_and_management_team.urls',namespace="events_and_management_team")),
    path('portal/logistics_and_operations_team/',include('logistics_and_operations_team.urls',namespace="logistics_and_operations_team")),
    path('portal/content_writing_and_publications_team/',include('content_writing_and_publications_team.urls',namespace="content_writing_and_publications_team")),
    path('portal/promotions_team/',include('promotions_team.urls',namespace="promotions_team")),
    path('portal/website_development_team/',include('website_development_team.urls',namespace='website_development_team')),
    path('portal/media_team/',include('media_team.urls',namespace='media_team')),
    path('portal/graphics_team/',include('graphics_team.urls',namespace="graphics_team")),
    path('portal/finance_and_corporate_team/',include("finance_and_corporate_team.urls",namespace="finanace_and_corporate_team")),
    path('portal/SC_AG/',include("chapters_and_affinity_group.urls",namespace="sc_ag")),
    re_path(r'^media_files/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}), 
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
]
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# handler404 = 'main_website.views.custom_404'

chapters_and_affinity_group/templates/Members/members_table.html
{% load static %}
{% block sc_ag_members_table %}

<!--Members Table For SC AG-->
<div class="box">
    <div class="box-header">
        
        {% if has_access_to_view_member_details %}
        <div style="text-align:right;">
            <button type="submit" class="btn btn-outline b-primary text-primary" data-toggle="modal" data-target="#m-s-a" ui-toggle-class="bounce" ui-target="#animate">Add New Members</button>
        </div>
        {% endif %}
        <small>This table holds the data of the Registered Members of {{sc_ag_info.group_name}}</small>
        <strong>Total Number of Registered Members in Database:<span style="color:blue;"> {{member_count}}</span></strong>
        <!--Messages-->
        <div style="justify-content:center; text-align:center;">
            {% if messages %}
                {% for message in messages %}
                    <h4{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</h4>
                {% endfor %}
            {% endif %}
        </div>
        <!--Messages End-->
        <br>
        <label style="margin-left:5px;">Search:</label>
        <input class="form-control w-75" type="text" id="searchInput" placeholder="Search Member by name" onkeyup="searchTable()">
    </div>
    <div class="table-responsive" style="max-height:300px; overflow-y:auto;">
    <table class="table table-bordered m-0" style="text-align:center;">
        <thead>
        <tr>
            <th style="text-align:center;">IEEE ID</th>
            <th style="text-align:center;">Name</th>
            <th style="text-align:center;">IEEE Email</th>
            <th style="text-align:center;">Current Position</th>
            <th style="text-align:center;">Current Team</th>
            {% if has_access_to_view_member_details %}
            <th style="text-align:center;">Action</th>
            {% endif %}
        </tr>
        </thead>
        <tbody>
        
            {% for member in sc_ag_members %}
            <tr>
                {% if has_access_to_view_member_details %}
                    <td><a style="text-decoration:none;color:#00629B;" href="{% url 'membership_development_team:member_details' member.member.ieee_id %}">{{member.member.ieee_id}}</a></td>
                {% else %}
                    <td>{{member.member.ieee_id}}</td>
                {% endif %}
                <td>{{ member.member.name  }}</td>
                <td>{{member.member.email_ieee}}</td>
                <td>{{member.position}}</td>
                <td>{{member.team}}</td>
                {% if has_access_to_view_member_details %}
                <td>
                    <button class="btn btn-outline b-danger text-danger" data-toggle="modal" data-target="#deleteModal" onclick="open_delete_modal('{{member.member.ieee_id}}')" style="margin-bottom:15px">Remove Member</button>
                </td>
                {% endif %}
            </tr>
            {% endfor %}
        </tbody>
    </table>
    </div>

    <!-- Confirm Delete Modal -->
    <div id="deleteModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="deleteModalLabel">Confirm Delete</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form method="POST">
                {% csrf_token %}
                <div class="modal-body">
                    <p>Are you sure you want to remove this member?</p>
                </div>
                <div class="modal-footer">
                    <input class="btn btn-outline b-danger text-danger has-value" name="remove_member" type="submit" value="Remove Member">
                    <input type="hidden" id="remove_sc_ag_member" name="remove_sc_ag_member"  value="" class="has-value">
                    <button class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                </div>
            </form>
            </div>
        </div>
    </div>


</div>


<!--Table Ends-->
<br>
<br>
{% if has_access_to_view_member_details %}
<!--Add modal-->
<div id="m-s-a" class="modal" data-backdrop="true">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title">Add Member To {{sc_ag_info.short_form}}!</h5>
        </div>
        <div class="modal-body p-lg">
          <p>Do select the Position of the Member Carefully!</p>
          <p>This will update the Members Position in the Database and also keep a record of the Member in the Panel.</p>
          <br>
        </div>
        <!--Position Input-->

        <!--Position Input Ends-->

        <!--Search table-->
        <form method="POST">
            {% csrf_token %}
            <div class="row">
                <div class="col-md-6">
                    <label style="margin-left:5px;">Select Position</label>
                    <select id="position" name="position">
                        <option value=0>-------------</option>
                        {% for position in positions %}
                            <option value={{position.id}}>{{ position.role }}</option>
                        {% endfor %} 
                    </select>
                </div>
                <div class="col-md-6">
                    <label style="margin-left:5px;">Select Team</label>
                    <select id="team" name="team">
                        <option value=0>-------------</option>
                        {% for team in teams %}
                            <option value={{team.pk}}>{{ team.team_name }}</option>
                        {% endfor %} 
                    </select>
                </div>
            </div>
            
            <br>
            
            <div class="table-container">
                <label style="margin-left: 5px;">Search</label>
                <input class="w-75" type="text" id="searchInput2" placeholder="Search Member" onkeyup="searchTable2()">
                <div class="table-wrapper">
                    <table class="table2" id="data2">
                        <thead>
                            <tr id="row">
                                <th>Name</th>
                                <th>IEEE ID</th>
                                <th>Current Position</th>
                                <th>Email</th>
                                <th>Select</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for member in insb_members %}
                            <tr>
                                <td>{{ member.name }}</td>
                                <td>{{ member.ieee_id }}</td>
                                <td>{{ member.position }}</td>
                                <td>{{ member.email_ieee }}</td>
                                <td>
                                    <input type="checkbox" id="select" name="member_select" value={{member.ieee_id}}>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        
            <div class="modal-footer">
            <button type="button" class="btn dark-white p-x-md" data-dismiss="modal">No</button>
                <input type="submit" class="btn primary p-x-md" name="add_sc_ag_member" value="Add Member"></input>  
            </div>
        </form>

      </div><!-- /.modal-content -->
    </div>
</div>
<!--Add modal ends-->
{% endif %}

<!---->
<script>
    function open_delete_modal(ieee_id){
        var element = document.getElementById("remove_sc_ag_member");
        element.value = ieee_id;
    }
</script>

<script>
    function searchTable() {
        // Declare variables
        var input, filter, table, tr, td, i, j, txtValue;
        input = document.getElementById("searchInput");
        filter = input.value.toUpperCase();
        table = document.querySelector("table");
        tr = table.getElementsByTagName("tr");
    
        // Loop through all table rows
        for (i = 0; i < tr.length; i++) {
            var rowVisible = false; // Flag to track if any column matches the search query in the current row
    
            // Loop through all columns in the current row
            for (j = 0; j < tr[i].getElementsByTagName("td").length; j++) {
                td = tr[i].getElementsByTagName("td")[j];
                if (td) {
                    txtValue = td.textContent || td.innerText;
                    if (txtValue.toUpperCase().indexOf(filter) > -1) {
                        rowVisible = true; // If a match is found in any column, set the flag to true
                    }
                }
            }
    
            // Set the display style for the row based on the flag
            if (rowVisible) {
                tr[i].style.display = "";
            } else {
                tr[i].style.display = "none";
            }
        }
    }
</script>
<script>
    function searchTable2() {
        // Declare variables
        var input, filter, table, tr, td, i, j, txtValue;
        input = document.getElementById("searchInput2");
        filter = input.value.toUpperCase();
        table = document.querySelector(".table2");
        tr = table.getElementsByTagName("tr");
    
        // Loop through all table rows
        for (i = 0; i < tr.length; i++) {
            var rowVisible = false; // Flag to track if any column matches the search query in the current row
    
            // Loop through all columns in the current row
            for (j = 0; j < tr[i].getElementsByTagName("td").length; j++) {
                td = tr[i].getElementsByTagName("td")[j];
                if (td) {
                    txtValue = td.textContent || td.innerText;
                    if (txtValue.toUpperCase().indexOf(filter) > -1) {
                        rowVisible = true; // If a match is found in any column, set the flag to true
                    }
                }
            }
    
            // Set the display style for the row based on the flag
            if (rowVisible) {
                tr[i].style.display = "";
            } else {
                tr[i].style.display = "none";
            }
        }
    }
</script>
{% endblock sc_ag_members_table %}

chapters_and_affinity_group/templates/Members/sc_ag_members.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>Members | {{sc_ag_info.group_name}}</title>
    <link rel="icon" href="{% static 'logos/logo.gif' %}"/>

    {% block common_css %}
        {% include "common_css.html" %}
    {% endblock common_css %}

    <style>
        body, html {
        
        margin: 0;
        
        align-items: center;
        justify-content: center;
        }

        .row {
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100%;
        }
        .row {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100%;
          }
          .btn-container {
            text-align: center;
          }
          
          .btn {
            max-width: 100%;
            width: auto;
            display: inline-block;
            white-space: normal; /* Allow text to wrap within the button */
            word-wrap: break-word; /* Break long words if necessary */
            font-size: 16px; /* Adjust the font size as needed */
          }
          .table-container {
            overflow: hidden; /* Hide table overflow */
        }
        
        .table-wrapper {
            max-height: 300px; /* Set the maximum height for scrolling */
            overflow: auto; /* Enable vertical scrolling */
        }
        
        table {
            width: 100%;
            border-collapse: collapse;
        }
        
        table, th, td {
            border: 1px solid #ccc;
        }
          
          /* Media query for smaller screens (adjust the breakpoint as needed) */
          @media (max-width: 768px) {
            .btn {
              width: 100%; /* Make the button full width on smaller screens */
            }
          }
        
    </style>
</head>
<body>
    <!-- ############ LAYOUT START-->
    <div class="app" id="app">

        <!-- aside -->
        <div id="aside" class="app-aside modal nav-dropdown">
  
  	        {% block sidebar %}
	            {% include 'users/sidebar.html' %}
  	        {% endblock %}
  
        </div>
        <!-- aside end -->
  
        <!-- navbar content -->
        <div id="content" class="app-content box-shadow-z0" role="main">
            {% block sc_ag_navbar %}
                {% include 'sc_ag_navbar.html' %}
            {% endblock sc_ag_navbar %}

        </div>
        <!--navbar content-->
        
        <!-- ############ PAGE START-->
        <div ui-view class="app-body" style="justify-content:center; margin-left:15%; margin-right:15%;" id="view">

            <!--Start from here-->
            <br>
            <br>
            <h2 style="justify-content:center;text-align:center;margin-bottom:15px;"><span style="">{{sc_ag_info.group_name}}</b></span><br> <span><b> Registered Members List</b></span> </h2>
            <br>

            <br>

            {% block sc_ag_members_table %}
                {% include "Members/members_table.html" %}
            {% endblock sc_ag_members_table %}


        </div>
        <!--PAGE END-->

        <!--Theme Switcher-->

        {% block theme_switcher %}
            {% include "theme_switcher.html" %}
        {% endblock theme_switcher %}
    
    </div>
    <!-- app end-->

    {% block common_js %}
        {% include "common_js.html" %}
    {% endblock common_js %}

</body>
</html>