api/urls.py
import imp
from django.urls import path,include
from api import views

app_name='api'

##defining the urls to work with

urlpatterns = [
    #path('members/',views.MemberList.as_view()),
    path('signup/',views.signupAppUser),
    path('login/',views.loginUser),
    
]

insb_central/urls.py
import imp
from django.urls import path,include
from . import views

app_name='insb_central'

##defining the urls to work with

urlpatterns = [
    
    #central_homeage
    path('',views.central_home, name='central_home'),
    #Event control page 
    path('event_control',views.event_control, name='event_control'),
    #Event Creation Form page 1
    path('create_event/page-1',views.event_creation_form_page1,name='event_creation_form1'),
    #Event Creation Form Page 2
    path("create_event/<int:event_id>/page-2", views.event_creation_form_page2, name="event_creation_form2"),
    #Event creation page 3
    path("create_event/<int:event_id>/page-3", views.event_creation_form_page3, name="event_creation_form3"),
    #Event control homepage
    path("event_control/event_home/<int:event_id>", views.event_control_homepage,name="event_homepage"),
    #teams page
    path('teams',views.teams,name='teams'),
    #team details page
    path('team_details/<str:pk>/<str:name>',views.team_details,name='team_details'),
    
]

insb_port/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    
    path('',include('main_website.urls',namespace='main_website')),
    path('portal/',include('port.urls',namespace='port')),
    path('api/',include('api.urls')),
    path('admin/', admin.site.urls),
    path('system/',include('system_administration.urls',namespace="system")),
    path('portal/users/',include('users.urls',namespace="users")),
    path('portal/notifications/',include('notification.urls',namespace="notification")),
    path('portal/recruitment/',include('recruitment.urls',namespace="recruitment")),
    path('portal/central_branch/',include('central_branch.urls',namespace='central_branch')),
    path('portal/membership_development_team/',include('membership_development_team.urls',namespace='membership_development_team')),
    path('portal/public_relation_team/',include('public_relation_team.urls',namespace='public_relation_team')),
    path('portal/system_administration',include('system_administration.urls',namespace='system_administration')),
    path('portal/events_and_management_team/',include('events_and_management_team.urls',namespace="events_and_management_team")),
    path('portal/logistics_and_operations_team/',include('logistics_and_operations_team.urls',namespace="logistics_and_operations_team")),
    path('portal/content_writing_and_publications_team/',include('content_writing_and_publications_team.urls',namespace="content_writing_and_publications_team")),
    path('portal/promotions_team/',include('promotions_team.urls',namespace="promotions_team")),
    path('portal/website_development_team/',include('website_development_team.urls',namespace='website_development_team')),
    path('portal/media_team/',include('media_team.urls',namespace='media_team')),
    path('portal/graphics_team/',include('graphics_team.urls',namespace="graphics_team")),
    path('portal/finance_and_corporate_team/',include("finance_and_corporate_team.urls",namespace="finanace_and_corporate_team")),
    path('portal/SC_AG/',include("chapters_and_affinity_group.urls",namespace="sc_ag")),
    re_path(r'^media_files/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}), 
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
]
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# handler404 = 'main_website.views.custom_404'

membership_development_team/urls.py
import imp
from django.urls import path,include
from . import views
from central_branch.views import task_edit,add_task,create_task,upload_task,task_home,forward_to_incharges

app_name='membership_development_team'

##defining the urls to work with

urlpatterns = [
   path('',views.md_team_homepage,name="md_team_homepage"),
   path('members/',views.insb_members_list,name="members_list"),
   path('member_details/<int:ieee_id>',views.member_details,name="member_details"),
   path('export_excel',views.generateExcelSheet_membersList,name="export_excel"),
   path('membership_renewal/',views.membership_renewal,name="membership_renewal"),
   path('membership_renewal/session/<str:pk>',views.renewal_session_data,name="renewal_session_data"),
   path('sc_ag_membership_renewal/session/<str:pk>/<str:sc_ag_primary>',views.sc_ag_renewal_session_data,name="sc_ag_renewal_session_data"),
   path('renewal_form/<str:pk>',views.membership_renewal_form,name="renewal_form"),
   path('renewal_form/<str:pk>/success',views.membership_renewal_form_success,name="renewal_form_success"),
   path('renewal_request/<str:pk>/<str:request_id>',views.renewal_request_details,name="request_details"), #using renewal request tables primary key 'id' as url because its the only unique matter in renewal process as no ieee id could be used
   path('export_excel_renewal_request/<str:session_id>',views.generateExcelSheet_renewal_requestList,name="export_excel_renewal_request"), #generate excel for renewal request
   path('getRenewalStats/',views.getRenewalStats,name="renewal_stats"),
   path('data_access',views.data_access,name="data_access"),
   path('insb_members/site_registration',views.site_registration_request_home,name="site_registration"),
   path("insb_site_registration_form",views.site_registration_form,name="site_registration_form"),
   path("insb_site_registration_form/success",views.confirmation_of_form_submission,name="confirmation"),
   path("insb_members/site_registration/request_details/<int:ieee_id>",views.site_registration_request_details,name="site_registration_request_details"),
   path("get_site_registration_stats/",views.getSiteRegistrationRequestStats,name="site_registration_stats"),
   path("insb_site_registration_form/faculty",views.site_registration_faculty,name="site_registration_faculty"),
   path("insb_site_registration_form/faculty/success",views.site_registration_faculty_confirmation,name="site_registration_faculty_confirmation"),

   #Task
   path('create_task/<int:team_primary>/',create_task,name="create_task_team"),
   path('task_home/<int:team_primary>/',task_home,name="task_home_team"),
   path('task/<int:task_id>/<int:team_primary>/',task_edit,name="task_edit_team"),
   path('task/<int:task_id>/upload_task/<int:team_primary>/',upload_task,name="upload_task_team"),
   path('task/<int:task_id>/forward_to_incharges/<int:team_primary>/',forward_to_incharges,name="forward_to_incharges"),
   path('task/<int:task_id>/add_task/<int:team_primary>/<int:by_coordinators>/',add_task,name="add_task_team"),
]

users/urls.py
from django.urls import path,include
from django.contrib.auth.views import LogoutView
from . import views
from django.conf import settings
from central_branch.views import upload_task, task_edit


app_name='users'

##defining the urls to work with

urlpatterns = [
    #include default auth urls
    #path('', include('django.contrib.auth.urls')),
    #loginpage
    path('login',views.login, name='login'),
    # signup user validation
    path('signup/validation/',views.signup_user_validation,name="signup_validation"),
    #signup page
    path('signup/<int:ieee_id>/<str:token>/',views.signup,name='signup'),
    #dashboard
    path('dashboard',views.dashboard,name='dashboard'),
    #logoutUser
    path('logout/',views.logoutUser,name='logoutUser'),
    #user Profile
    path('profile',views.profile_page,name='profile'),
    #user Profile settings
    path('change_password',views.change_password,name='change_password'),
    #user Profile update information
    path('update_information',views.update_information,name='update_information'),
    #forgot password
    path('username_validation',views.forgotPassword_getUsername,name="fp_validation"), #fp=forgot password, this page just checks if the username is registered or not
    #forgot password
    path('reset_password/<str:username>/<str:token>/',views.forgotPassword_resetPassword,name="reset_password"),
    #Invalid URL Handling
    path('invalid_url',views.invalidURL,name="invalid_url"), #this page will prompt if an user has used an "used" or invalid url
    #my task url
    path('my_tasks/',views.my_tasks,name="my_tasks"),
    path('my_tasks/<int:task_id>/',task_edit,name="edit_task_user"),
    path('my_tasks/<int:task_id>/upload_tasks/',upload_task,name="upload_task_user"),
 
]

insb_central/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.models import User,auth
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from . import renderData
from port.models import Teams,Chapters_Society_and_Affinity_Groups
from django.db import connection
from django.db.utils import IntegrityError
from django.core.exceptions import ObjectDoesNotExist
from recruitment.models import recruited_members
import csv,datetime
from users.ActiveUser import ActiveUser
from django.db import DatabaseError
from system_administration.render_access import Access_Render
from insb_central.renderData import Branch
from events_and_management_team.renderData import Events_And_Management_Team
from logistics_and_operations_team.renderData import LogisticsTeam
from . models import Events,InterBranchCollaborations,IntraBranchCollaborations
from events_and_management_team.models import Venue_List,Permission_criteria
from insb_central.renderData import Branch


# Create your views here.

def central_home(request):
    user=request.user
    has_access=Access_Render.system_administrator_superuser_access(user.username)
    if (has_access):
        #renderData.Branch.test_google_form()
        return render(request,'central_home.html')
    else:
        return render(request,"access_denied2.html")

@login_required
def event_control(request):
    all_insb_events=renderData.Branch.load_all_events()
    context={
        'events':all_insb_events,
    }
    if(request.method=="POST"):
        if request.POST.get('create_new_event'):
            print("Create")
    
    return render(request,'event_page.html',context)

@login_required
def event_creation_form_page1(request):
    
    #######load data to show in the form boxes#########
    
    #loading super/mother event at first
    super_events=Branch.load_all_mother_events()


    
    context={
        'super_events':super_events,
    }
    
    if(request.method=="POST"):
        if(request.POST.get('next')):
            super_event_name=request.POST.get('super_event')
            
            event_name=request.POST['event_name']
            event_description=request.POST['event_description']
            probable_date=request.POST['probable_date']
            final_date=request.POST['final_date']
            
            get_event=renderData.Branch.register_event_page1(
                super_event_name=super_event_name,
                event_name=event_name,
                event_description=event_description,
                probable_date=probable_date,
                final_date=final_date)
            
            if(get_event)==False:
                messages.info(request,"Database Error Occured! Please try again later.")
            else:
                #if the method returns true, it will redirect to the new page
                return redirect('insb_central:event_creation_form2',get_event)


                
            
                
        elif(request.POST.get('cancel')):
            return redirect('insb_central:event_control')
    return render(request,'event_creation_form1.html',context)

@login_required
def event_creation_form_page2(request,event_id):
    #loading all inter branch collaboration Options
    inter_branch_collaboration_options=Branch.load_all_inter_branch_collaboration_options()
    context={
        'inter_branch_collaboration_options':inter_branch_collaboration_options,
    }
    if request.method=="POST":
        if(request.POST.get('next')):
            inter_branch_collaboration_list=request.POST.getlist('inter_branch_collaboration')
            intra_branch_collaboration=request.POST['intra_branch_collaboration']
            
            if(renderData.Branch.register_event_page2(
                inter_branch_collaboration_list=inter_branch_collaboration_list,
                intra_branch_collaboration=intra_branch_collaboration,
                event_id=event_id)):
                return redirect('insb_central:event_creation_form3',event_id)
            else:
                messages.info(request,"Database Error Occured! Please try again later.")

        elif(request.POST.get('cancel')):
            return redirect('insb_central:event_control')


    return render(request,'event_creation_form2.html',context)

def event_creation_form_page3(request,event_id):
    #loading all venues from the venue list from event management team database
    venues=Events_And_Management_Team.getVenues()
    #loading all the permission criterias from event management team database
    permission_criterias=Events_And_Management_Team.getPermissionCriterias()

    context={
        'venues':venues,
        'permission_criterias':permission_criterias,
    }
    if request.method=="POST":
        if request.POST.get('next'):
            #getting the venues for the event
            venue_list_for_event=request.POST.getlist('event_venues')
            #getting the permission criterias for the event
            permission_criterias_list_for_event=request.POST.getlist('permission_criteria')
            
            #updating data collected from part3 for the event
            update_event_details=renderData.Branch.register_event_page3(venue_list=venue_list_for_event,permission_criteria_list=permission_criterias_list_for_event,event_id=event_id)
            #if return value is false show an error message
            if(update_event_details==False):
                messages.info(request, "An error Occured! Please Try again!")
            else:
                return redirect('insb_central:event_control')

    return render(request,'event_creation_form3.html',context)


def event_control_homepage(request,event_id):
    
    return render(request,'event_control_homepage.html')

def teams(request):
    
    '''
    Loads all the existing teams in the branch
    Gives option to add or delete a team
    '''
    
    #load teams from database
    
    teams=renderData.Branch.load_teams()
    team_list=[]
    for team in teams:
        team_list.append(team)
    context={
        'team':team_list
    }
    
    return render(request,'teams.html',context=context)
def team_details(request,pk,name):
    
    '''Detailed panel for the team'''
    
    #load data of current team Members
    team_members=renderData.Branch.load_team_members(pk)
    #load all the roles and positions from database
    positions=renderData.Branch.load_roles_and_positions()
    #loading all members of insb
    insb_members=renderData.Branch.load_all_insb_members()
    
    members_to_add=[]
    position=12 #assigning default to volunteer
    if request.method=='POST':
        if(request.POST.get('add_to_team')):
            #Checking if a button is clicked
            if(request.POST.get('member_select')):
                members_to_add=request.POST.getlist('member_select')
                position=request.POST.get('position')
                #ADDING MEMBER TO TEAM
                for member in members_to_add:
                    if(renderData.Branch.add_member_to_team(ieee_id=member,team=pk,position=position)):
                        messages.info(request,"Member Added to the team!")
                    elif(renderData.Branch.add_member_to_team(ieee_id=member,team=pk,position=position)==False):
                        messages.info(request,"Member couldn't be added!")
                    elif(renderData.Branch.add_member_to_team(ieee_id=member,team=pk,position=position)==DatabaseError):
                        messages.info(request,"An internal Database Error Occured! Please try again!")
                return redirect('insb_central:team_details',pk,name)

    context={
        'team_name':name,
        'team_members':team_members,
        'positions':positions,
        'insb_members':insb_members,
        
    }
    return render(request,'team_details_page.html',context=context)

insb_central/templates/access_denied2.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Access Denied</title>
        <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
            crossorigin="anonymous"
        ></script>
        <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
            crossorigin="anonymous"
        />
        <link
            rel="stylesheet"
            href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css"
            integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w=="
            crossorigin="anonymous"
            referrerpolicy="no-referrer"
        />
        <link rel="stylesheet" href="{% static 'access_denied.css' %}" />
    </head>

    <body>
        <main>
            <nav class="navbar navbar-expand-lg">
                <div class="container-fluid">
                    <a class="navbar-brand" href="#">
                        <img
                            class="img-fluid"
                            src="{% static 'logo.gif' %}"
                            alt="IEEE_logo"
                            width="40"
                            height="40"
                        />
                    </a>
                    <!-- <a class="navbar-brand" href="#">IEEE</a> -->
                    <button
                        class="navbar-toggler bg-warning"
                        type="button"
                        data-bs-toggle="collapse"
                        data-bs-target="#navbarNavAltMarkup"
                        aria-controls="navbarNavAltMarkup"
                        aria-expanded="false"
                        aria-label="Toggle navigation"
                    >
                        <span class="navbar-toggler-icon">
                            <i class="fa-solid fa-bars mt-1"></i>
                        </span>
                    </button>
                    <div
                        class="collapse navbar-collapse"
                        id="navbarNavAltMarkup"
                    >
                        <div class="navbar-nav ms-auto">
                            <a class="nav-link navLi"  href="{% url 'users:dashboard' %}">Dashboard</a>
                            <a class="nav-link navL" href="{% url 'insb_central:central_home' %}"><small>Branch</small></a>
                            <a class="nav-link navLi" href="#"><small>Event & Management</small></a>
                            <a class="nav-link navLi" href="#"><small>Logistics</small></a>
                            <a class="nav-link navLi" href="#"><small>Content</small></a>
                            <a class="nav-link navLi" href="#"><small>Promotion</small></a>
                            <a class="nav-link navLi" href="{% url 'membership_development_team:md_team_homepage' %}"><small>Membership Development</small></a>
                            <a class="nav-link navLi" href="#"><small>Website development</small></a>
                            <a class="nav-link navLi" href="#"><small>Media</small></a>
                            <a class="nav-link navLi" href="#"><small>Graphics</small></a>
                            <a class="nav-link navLi" href="#"><small>Finance</small></a>
                            <a class="nav-link navLi" href="#"><small>Public Relation</small></a>
                        </div>
                    </div>
                </div>
            </nav>
            <section class="banner">
                <section class="container">
                    <div class="row">
                        <div
                            class="d-flex flex-column justify-content-center h-100"
                        >
                            <h1
                                class="text-center fw-bold mt-3 text-uppercase text-white"
                            >
                                <span style="color:red">View Restricted!</span>
                            </h1>
                            
                            <p class="text-white warning">
                                Sorry! You are not allowed to View this page.<br>
                                If you have Permission to view this page, please contact the <span style="color:yellow;"> Co-Ordinator </span>or <span style="color:yellow;"> System Administrators!</span>

                            </p>
                            
                        </div>

                    
                    </div>
                
                        
                    </div>
                </section>
            </section>
        </main>

        <footer class="py-3 right-bg text-white text-center">
            <small>&copy; All Rights Reserved by IEEE NSU STUDENT BRANCH</small>
        </footer>
        <!-- footer end -->
    </body>
    
</html>

insb_central/templates/central_home.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>INSB-Central</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
        <h1>
            Hello and Welcome to the Central Control Panel of IEEENSUSB
        </h1>
        <button><a href="" class="">INSB Registered Members</a></button>
        <button><a href="{% url 'insb_central:event_control' %}" class="">Events</a></button>
        <script src="" async defer></script>
    </body>
</html>

insb_central/templates/event_control_page.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>New Event</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
        <h1>Central event control page for INSB</h1>
        <button><a href="" class="">Create a new Event</a></button>
        <script src="" async defer></script>
    </body>
</html>

insb_central/templates/event_page.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>New Event</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
        <h1>Central event control page for INSB</h1>
        <button><a href="{% url 'insb_central:event_creation_form1' %}" class="">Create a new Event</a></button>
        <button><a href="" class="">Create a new Super Event</a></button>
        <br><br>
        <h1>Event List</h1>
        
        <label>Search: </label>
        <input type="text" onkeyup="searchfunction()" id="search" placeholder="Search with any credentials">
        
        <br>
        <table id="event_table">
            <thead>
                <tr id="table_row">
                    <th>Event Name</th>
                    <th>Event Organiser</th>
                    <th>Probable Date of Event</th>
                    <th>Final Date of Event</th>
                    
                </tr>
            </thead>
        {% comment %} This block is responsible for loading all the members recruited on that session and passes their id to the url as well as their data to the recruitee_details function {% endcomment %}
        {% for event in events %}
            <tr>
                <td><a href="{% url 'insb_central:event_homepage' event.id %}">{{event.event_name }}</a></td>
                <td>{{ event.event_organiser }}</td>
                <td>{{ event.probable_date }}</td>
                <td>{{ event.final_date }}</td>
                
            </tr>
        {% endfor %}
        </table>
        <p id="no_data"></p>

        <script>
            function searchfunction(){
                let input,filter,table,tr,td,j;
                input=document.getElementById("search");
                filter=input.value.toUpperCase();
                table=document.getElementById("event_table");
                tr=table.getElementsByTagName("tr");
                
                for(j=0;j<tr.length;j++){
                    td=tr[j].getElementsByTagName("td");
                    message=document.getElementById("no_data");
        
                    if(td.length > 0){
                        if(td[0].innerHTML.toLocaleUpperCase().indexOf(filter)> -1 ||
                        td[1].innerHTML.toLocaleUpperCase().indexOf(filter)> -1 ||
                        td[2].innerHTML.toLocaleUpperCase().indexOf(filter)> -1 ||
                        td[3].innerHTML.toLocaleUpperCase().indexOf(filter)> -1){
                        tr[j].style.display="";
                        message.innerHTML="";
                    }
                            else{
                                tr[j].style.display="none";
                            }
                    
                    }        
                    if(td.length==0){
                        message.innerHTML="Event not found!";
                    }
                }
            }
        </script>
    </body>
</html>

insb_central/templates/teams.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        <h1>Page For Teams</h1>
        <form method="POST" action=''>
            {% csrf_token %}
            <div class="d-grid pt-3">
                <input type="text" placeholder="Create New Team" class="Form-cont my-1 p-1" Required name='recruitment_session'>
            </div>
            <button type="submit" class="log-btn" onclick=''>
                Create
           </button>
        </form>
        <br>
        
        <br>
        <label>Search Sessions: </label>
        <input type="text" onkeyup="searchfunction()" id="search" placeholder="Enter session">
    
        <br>
        <ul id="ul">
            {% for team in team %}
            <li id="li"><a href="{% url 'insb_central:team_details' team.id team.team_name %}" >{{team.team_name}}</a></li>
            {% endfor %}
        </ul>
        <script>
            function searchfunction(){
                let input,filter,j;
                input=document.getElementById("search");
                filter=input.value.toUpperCase();
                let ul=document.getElementById("ul");
                let li=ul.getElementsByTagName("li");

                for(j=0;j<li.length;j++){
                    message=document.getElementById("no_data");
                    let a=li[j].getElementsByTagName('a')[0];
                    let textValue=a.textContent || a.innerHTML;
                    if(textValue.toUpperCase().indexOf(filter) > -1){
                        li[j].style.display='';
                        
                    }                           
                    else{
                        li[j].style.display="none";

                    }

                }
            }
        
        </script>
    </body>
</html>