api/urls.py
import imp
from django.urls import path,include
from api import views

app_name='api'

##defining the urls to work with

urlpatterns = [
    #path('members/',views.MemberList.as_view()),
    path('signup/',views.signupAppUser),
    path('login/',views.loginUser),
    
]

insb_port/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    
    path('',include('main_website.urls',namespace='main_website')),
    path('portal/',include('port.urls',namespace='port')),
    path('api/',include('api.urls')),
    path('admin/', admin.site.urls),
    path('system/',include('system_administration.urls',namespace="system")),
    path('portal/users/',include('users.urls',namespace="users")),
    path('portal/notifications/',include('notification.urls',namespace="notification")),
    path('portal/recruitment/',include('recruitment.urls',namespace="recruitment")),
    path('portal/central_branch/',include('central_branch.urls',namespace='central_branch')),
    path('portal/membership_development_team/',include('membership_development_team.urls',namespace='membership_development_team')),
    path('portal/public_relation_team/',include('public_relation_team.urls',namespace='public_relation_team')),
    path('portal/system_administration',include('system_administration.urls',namespace='system_administration')),
    path('portal/events_and_management_team/',include('events_and_management_team.urls',namespace="events_and_management_team")),
    path('portal/logistics_and_operations_team/',include('logistics_and_operations_team.urls',namespace="logistics_and_operations_team")),
    path('portal/content_writing_and_publications_team/',include('content_writing_and_publications_team.urls',namespace="content_writing_and_publications_team")),
    path('portal/promotions_team/',include('promotions_team.urls',namespace="promotions_team")),
    path('portal/website_development_team/',include('website_development_team.urls',namespace='website_development_team')),
    path('portal/media_team/',include('media_team.urls',namespace='media_team')),
    path('portal/graphics_team/',include('graphics_team.urls',namespace="graphics_team")),
    path('portal/finance_and_corporate_team/',include("finance_and_corporate_team.urls",namespace="finanace_and_corporate_team")),
    path('portal/SC_AG/',include("chapters_and_affinity_group.urls",namespace="sc_ag")),
    re_path(r'^media_files/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}), 
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
]
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# handler404 = 'main_website.views.custom_404'

public_relation_team/urls.py
from django.urls import path,include
from . import views
from central_branch.views import task_edit,add_task,create_task,upload_task,task_home,forward_to_incharges



app_name='public_relation_team'

urlpatterns = [
    path('',views.team_home_page,name='team_homepage'),
    #Event control page 
    path('event_control/',views.event_control,name="event_control"),
    #Event Creation Form page 1
    path('create_event/page-1',views.event_creation_form_page1,name='event_creation_form1'),
    #Event Creation Form Page 2
    path("create_event/<int:event_id>/page-2", views.event_creation_form_page2, name="event_creation_form2"),
    #Event creation page 3
    path("create_event/<int:event_id>/page-3", views.event_creation_form_page3, name="event_creation_form3"),
    #Super Event Creation Form
    path('create_super_event/',views.super_event_creation,name="super_event_creation"),
    #Manage Event page
    path('manage_event/',views.manage_event,name="manage_event"),
    #Event Dashboard
    path('event_dashboard/<int:event_id>',views.event_dashboard,name='event_dashboard'),
    #Manage Team
    path('manage_team/',views.manage_team,name="manage_team"),
    #Manage website Homepage
    path('manage_website/',views.manageWebsiteHome,name="manage_website_home"),

    #Task
    path('create_task/<int:team_primary>/',create_task,name="create_task_team"),
    path('task_home/<int:team_primary>/',task_home,name="task_home_team"),
    path('task/<int:task_id>/<int:team_primary>/',task_edit,name="task_edit_team"),
    path('task/<int:task_id>/upload_task/<int:team_primary>/',upload_task,name="upload_task_team"),
    path('task/<int:task_id>/forward_to_incharges/<int:team_primary>/',forward_to_incharges,name="forward_to_incharges"),
    path('task/<int:task_id>/add_task/<int:team_primary>/<int:by_coordinators>/',add_task,name="add_task_team"),
]

public_relation_team/models.py
from django.db import models
from users.models import Members
from django.core.files.storage import FileSystemStorage

# Create your models here.



class Manage_Team(models.Model):

    ieee_id = models.ForeignKey(Members,null=False,blank=False,on_delete=models.CASCADE,verbose_name="IEEE ID")
    manage_team_access = models.BooleanField(default=False,null=False,blank=False,verbose_name="Team Access")
    manage_email_access = models.BooleanField(default=False,null=False,blank=False,verbose_name="Email Access")

    class Meta:

        verbose_name = "Manage Team Access"

    def __str__(self):
        return str(self.ieee_id)

# class Email_Draft(models.Model):
#     email_unique_id = models.CharField(null=False,blank=False,max_length=20)
#     subject = models.TextField(blank=True,null=True)
#     drafts = models.JSONField(null=True,blank=True,default=dict)
#     timestamp = models.DateTimeField(null=False,blank=False,auto_now_add=True)

#     class Meta:
#         verbose_name = "Email Draft"

#     def __str__(self):
#         return str(self.email_unique_id)

public_relation_team/views.py
from django.shortcuts import render,redirect
from django.conf import settings
from django.views import View
from central_branch import renderData
from django.contrib.auth.decorators import login_required
from central_events.models import SuperEvents,Events,InterBranchCollaborations,IntraBranchCollaborations,Event_Venue
from central_branch.renderData import Branch
from django.contrib import messages
from events_and_management_team.renderData import Events_And_Management_Team
from .renderData import PRT_Data
from system_administration.render_access import Access_Render
from system_administration.models import system
from users.models import Members
from port.models import Roles_and_Position
from .models import Manage_Team
from datetime import datetime
from users import renderData
import json
from users.renderData import LoggedinUser
from django.utils.datastructures import MultiValueDictKeyError
from .render_email import PRT_Email_System
from port.renderData import PortData
from users.renderData import PanelMembersData,member_login_permission
from chapters_and_affinity_group.renderData import SC_AG_Info
import logging
from system_administration.system_error_handling import ErrorHandling
from datetime import datetime
import traceback
from central_branch import views as cv
# Create your views here.

logger=logging.getLogger(__name__)

@login_required
@member_login_permission
def team_home_page(request):

    try:

        sc_ag=PortData.get_all_sc_ag(request=request)
        current_user=renderData.LoggedinUser(request.user) #Creating an Object of logged in user with current users credentials
        user_data=current_user.getUserData() #getting user data as dictionary file
        # get team members
        get_team_members=PRT_Data.get_team_members_with_position()
        context={
            'all_sc_ag':sc_ag,
            'co_ordinators':get_team_members[0],
            'incharges':get_team_members[1],
            'core_volunteers':get_team_members[2],
            'team_volunteers':get_team_members[3],
            'user_data':user_data,
            'media_url':settings.MEDIA_URL,
        }
        return render(request,"public_relation_team/team_homepage.html",context)
    
    except Exception as e:
        logger.error("An error occurred at {datetime}".format(datetime=datetime.now()), exc_info=True)
        ErrorHandling.saveSystemErrors(error_name=e,error_traceback=traceback.format_exc())
        return cv.custom_500(request)

@login_required
@member_login_permission
def event_control(request):

    try:

        all_insb_events=renderData.Branch.load_all_events()
        context={
            'events':all_insb_events,
        }
        if(request.method=="POST"):
            if request.POST.get('create_new_event'):
                print("Create")
        
        return render(request,'public_relation_team/event/event_page.html',context)
    
    except Exception as e:
        logger.error("An error occurred at {datetime}".format(datetime=datetime.now()), exc_info=True)
        ErrorHandling.saveSystemErrors(error_name=e,error_traceback=traceback.format_exc())
        return cv.custom_500(request)

@login_required
@member_login_permission
def super_event_creation(request):

    '''function for creating super event'''

    try:


        if request.method == "POST":

            '''Checking to see if either of the submit or cancelled button has been clicked'''

            if (request.POST.get('Submit')):

                '''Getting data from page and saving them in database'''

                super_event_name = request.POST.get('super_event_name')
                super_event_description = request.POST.get('super_event_description')
                start_date = request.POST.get('probable_date')
                end_date = request.POST.get('final_date')
                saving_data = SuperEvents(super_event_name=super_event_name,super_event_description=super_event_description,start_date=start_date,end_date=end_date)
                saving_data.save()
                return redirect('public_relation_team:manage_event')
            
            elif (request.POST.get('cancel')):
                return redirect('public_relation_team:manage_event')
            
        return render(request,"public_relation_team/event/super_event_creation_form.html")
    
    except Exception as e:
        logger.error("An error occurred at {datetime}".format(datetime=datetime.now()), exc_info=True)
        ErrorHandling.saveSystemErrors(error_name=e,error_traceback=traceback.format_exc())
        return cv.custom_500(request)
    
@login_required
@member_login_permission
def event_creation_form_page1(request):
    
    #######load data to show in the form boxes#########

    try:

    
        #loading super/mother event at first
        super_events=Branch.load_all_mother_events()
        event_types=Branch.load_all_event_type()

        
        context={
            'super_events':super_events,
            'event_types':event_types,
        }
        
        
        if(request.method=="POST"):
            if(request.POST.get('next')):
                super_event_name=request.POST.get('super_event')
                event_name=request.POST['event_name']
                event_description=request.POST['event_description']
                probable_date=request.POST['probable_date']
                final_date=request.POST['final_date']
                
                get_event=renderData.Branch.register_event_page1(
                    super_event_name=super_event_name,
                    event_name=event_name,
                    event_description=event_description,
                    probable_date=probable_date,
                    final_date=final_date)
                
                if(get_event)==False:
                    messages.info(request,"Database Error Occured! Please try again later.")
                else:
                    #if the method returns true, it will redirect to the new page
                    return redirect('public_relation_team:event_creation_form2',get_event)


                    
                
                    
            elif(request.POST.get('cancel')):
                return redirect('public_relation_team:manage_event')
        return render(request,'public_relation_team/event/event_creation_form1.html',context)
    
    except Exception as e:
        logger.error("An error occurred at {datetime}".format(datetime=datetime.now()), exc_info=True)
        ErrorHandling.saveSystemErrors(error_name=e,error_traceback=traceback.format_exc())
        return cv.custom_500(request)

@login_required
@member_login_permission
def event_creation_form_page2(request,event_id):

    try:

        #loading all inter branch collaboration Options
        inter_branch_collaboration_options=Branch.load_all_inter_branch_collaboration_options()
        context={
            'inter_branch_collaboration_options':inter_branch_collaboration_options,
        }
        if request.method=="POST":
            if(request.POST.get('next')):
                inter_branch_collaboration_list=request.POST.getlist('inter_branch_collaboration')
                intra_branch_collaboration=request.POST['intra_branch_collaboration']
                
                if(renderData.Branch.register_event_page2(
                    inter_branch_collaboration_list=inter_branch_collaboration_list,
                    intra_branch_collaboration=intra_branch_collaboration,
                    event_id=event_id)):
                    return redirect('public_relation_team:event_creation_form3',event_id)
                else:
                    messages.info(request,"Database Error Occured! Please try again later.")

            elif(request.POST.get('cancel')):
                return redirect('public_relation_team:manage_event')


        return render(request,'public_relation_team/event/event_creation_form2.html',context)
    
    except Exception as e:
        logger.error("An error occurred at {datetime}".format(datetime=datetime.now()), exc_info=True)
        ErrorHandling.saveSystemErrors(error_name=e,error_traceback=traceback.format_exc())
        return cv.custom_500(request)
@login_required
@member_login_permission
def event_creation_form_page3(request,event_id):

    try:

        #loading all venues from the venue list from event management team database
        venues=Events_And_Management_Team.getVenues()
        #loading all the permission criterias from event management team database
        permission_criterias=Events_And_Management_Team.getPermissionCriterias()

        context={
            'venues':venues,
            'permission_criterias':permission_criterias,
        }
        if request.method=="POST":
            if request.POST.get('next'):
                #getting the venues for the event
                venue_list_for_event=request.POST.getlist('event_venues')
                #getting the permission criterias for the event
                permission_criterias_list_for_event=request.POST.getlist('permission_criteria')
                
                #updating data collected from part3 for the event
                update_event_details=renderData.Branch.register_event_page3(venue_list=venue_list_for_event,permission_criteria_list=permission_criterias_list_for_event,event_id=event_id)
                #if return value is false show an error message
                if(update_event_details==False):
                    messages.info(request, "An error Occured! Please Try again!")
                else:
                    return redirect('public_relation_team:manage_event')

        return render(request,'public_relation_team/event/event_creation_form3.html',context)
    
    except Exception as e:
        logger.error("An error occurred at {datetime}".format(datetime=datetime.now()), exc_info=True)
        ErrorHandling.saveSystemErrors(error_name=e,error_traceback=traceback.format_exc())

public_relation_team/templates/public_relation_team/event/manage_event.html
<!DOCTYPE html>
{% load static %}
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Manage Event</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="">
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700;800&display=swap');

        * {
            padding: 0;
            margin: 0;
            box-sizing: border-box;
        }

        body {
            font-family: 'Poppins', sans-serif;
            background-image: linear-gradient(90deg, #67b8e4, #060c4d)
        }

        /* navbar */
        header {
            background-color: #050D3A;
        }
        
        .navbar li {
            list-style: none;
        }

        .navbar a {
            color: #fff;
            text-decoration: none;
        }

        .navbar {
            min-height: 70px;
            display: flex;
            justify-content: space-between;
            align-items: center;
            padding: 0 20px;
        }

        .nav-menu {
            display: flex;
            gap: 20px;
        }

        .nav-link {
            transition: 0.3s ease;
        }

        .nav-link:hover {
            color: rgb(255, 183, 0);
        }

        .hamburger {
            display: none;
            cursor: pointer;
        }

        .bar {
            display: block;
            width: 25px;
            height: 3px;
            margin: 5px auto;
            -webkit-transition: all 0.3s ease-in-out;
            transition: all 0.3s ease-in-out;
            background-color: #fff;
        }

        @media(max-width: 1560px) {
            .hamburger {
                display: block;
            }

            .hamburger.active .bar:nth-child(2) {
                opacity: 0;
            }

            .hamburger.active .bar:nth-child(1) {
                transform: translateY(8px) rotate(45deg);
            }

            .hamburger.active .bar:nth-child(3) {
                transform: translateY(-8px) rotate(-45deg);
            }

            .nav-menu {
                position: absolute;
                top: -1070px;
                left: 0;
                width: 100%;
                gap: 0;
                flex-direction: column;
                background-color: #050D3A;
                text-align: left;
                transition: 0.7s;
                padding: 0 20px;
            }

            .nav-item {
                margin: 16px 0;
            }

            .nav-menu.active {
                top: 70px;
            }

            .container {
                padding-top: 0px;
                transition: 0.8s;
            }

            .container.active {
                padding-top: 700px;
            }
        }
       

        /* body */
        .header {
            padding: 60px 40px;
            text-align: center;
            color: rgb(255, 255, 255);
            text-transform: capitalize;
        }

        .create_event_button {
            display: flex;
            flex-direction: row;
            column-gap: 2rem;
            row-gap: 2rem;
            justify-content: center;
            flex-wrap: wrap;
            align-items: center;
        }

        .create_event_button button {
            width: 230px;
            height: 50px;
            background-color: #050D3A;
            border: 2px solid black;
            box-shadow: 3px 9px 10px 1px rgba(0, 0, 0, 0.68);
            transition: 0.3s;
        }

        .create_event_button button a {
            text-decoration: none;
            color: #fff;
            font-size: 15px bold;
            text-transform: capitalize;
        }

        .create_event_button button:hover {
            background-color: #050D3A;
            scale: 1.2;
        }

        .create_event_button button a:hover {
            color: rgb(255, 223, 40);
            transition: all 0.2s;
        }

        .event {
            display: flex;
            margin: 20px;
            max-height: 55vh;
            border-radius: .8rem;
            flex-direction: column;
            background-color: #fff;
            box-shadow: 0 .4rem .8rem #0005;
            backdrop-filter: blur(7px);
            overflow: hidden;
        }

        .event_header {
            width: 100%;
            height: 18%;
            background-color: #fff4;
            padding: .8rem 1rem;
        }

        .event_search {
            padding: 10px 0;
        }

        .event_search label {
            font-size: 20px;
        }

        .event_search input {
            font-size: 20px;
            width: 70%;
            max-width: 50vh;
        }

        .event_info {
            width: 95%;
            max-width: calc(89% - .8rem);
            margin: .4rem auto;
            border-radius: .6rem;
            overflow: auto;
            display: flex;
            flex-direction: column;
        }

        .event_info::--webkit-scrollbar-thumb {
            border-radius: .5rem;
            background-color: #0004;
            visibility: hidden;
        }

        .event_info:hover::--webkit-scrollbar-thumb {
            visibility: visible;
        }

        .event_info table,
        th,
        td {
            border-collapse: collapse;
            padding: 1rem;
        }

        .event_info thead th {
            position: sticky;
            top: 0;
            left: 0;
            text-align: left;
            background-color: #050D3A;
            color: #fff;
        }

        .event_info tbody tr:nth-child(even) {
            background-color: #0000000b;
        }

        .event_info tbody tr:hover {
            background-color: rgba(142, 181, 220, 0.4);
        }
    </style>
</head>

<body>
    <header>
        <nav class="navbar">
            <a href="#" class="nav-logo"><img src="{% static 'logo.gif' %}" alt="IEEE_logo" width="40" height="40"></a>
            <ul class="nav-menu">
                <li class="nav-item">
                    <a href="#" class="nav-link">Home</a>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link">Central Branch</a>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link">Event & Management</a>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link">Logistics</a>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link">Content</a>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link">Promotion</a>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link">Membership Development</a>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link">Website Development</a>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link">Media</a>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link">Graphics</a>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link">Finance</a>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link">Public Relation</a>
                </li>
            </ul>
            <div class="hamburger">
                <span class="bar"></span>
                <span class="bar"></span>
                <span class="bar"></span>
            </div>
        </nav>
    </header>
    <div class="container">
        <h1 class="header">Manage Events</h1>
        <div class="container">
            <div class="create_event_button">
                <button><a href="{% url 'public_relation_team:event_creation_form1' %}" class="">Create a new Event</a></button>
                <button><a href="{% url 'public_relation_team:super_event_creation' %}" class="">Create a new Super Event</a></button>
            </div>
            <br><br>
            
        </div>
        <div class="event">
            <section class="event_header">
                <h1>Event List</h1>
                <div class="event_search">
                    <label>Search: </label>
                    <input type="text" onkeyup="searchfunction()" id="search" placeholder="Search with any credentials">
                </div>
            </section>
            <br>
            {% for messages in messages %}
                <p class="text-white text-center">{{messages}}</p>
            {% endfor %}
            <section class="event_info">
                <table id="event_table">
                    <thead>
                        <tr id="table_row">
                            <th>Event Name</th>
                            <th>Event Organiser</th>
                            <th>Probable Date of Event</th>
                            <th>Final Date of Event</th>
                            <th>Publish to Web</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% comment %} This block is responsible for loading all the members recruited on that session
                        and passes their id to the url as well as their data to the recruitee_details function {% endcomment %}
                        {% for event in events %}
                        <tr>
                            <form method="POST">
                                {% csrf_token %}
                            <td><a href="{% url 'public_relation_team:event_dashboard' event.id %}">{{event.event_name }}</a></td>
                            <td>{{ event.event_organiser }}</td>
                            <td>{{ event.probable_date }}</td>
                            <td>{{ event.final_date }}</td>
                            
                            <td>
                                {% if event.publish_in_main_web %}
                                    <input type="checkbox" checked="True" class="checkbox" value="publish_in_main_web" name="publish_in_main_web">
                                    <br>
                                {% else %}
                                    <input type="checkbox" class="checkbox" value="publish_in_main_web" name="publish_in_main_web">
                                    <br>
                                {% endif %}  
                            </td>
                            <td>
                                <input class="btn btn-warning" name="update" type="submit" value="Update">
                                <input type="hidden" name="event_id" value={{event.id}}>
                            </td>
                        </form>
                        </tr>
                        {% endfor %}
                        
                   
                    </tbody>
                </table>
                
                <p id="no_data"></p>
            </section>
        </div>
    </div>

    <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->

    <script>
        const hamburger = document.querySelector(".hamburger");
        const navMenu = document.querySelector(".nav-menu");
        const container = document.querySelector(".container");

        hamburger.addEventListener("click", () => {
            hamburger.classList.toggle("active");
            navMenu.classList.toggle("active");
            container.classList.toggle("active");
        })

        document.querySelectorAll(".navlink").forEach(n => n.addEventListener("click", () => {
            hamburger.classList.remove("active");
            navMenu.classList.remove("active");
            container.classList.toggle("active");
        }))
        function searchfunction() {
            let input, filter, table, tr, td, j;
            input = document.getElementById("search");
            filter = input.value.toUpperCase();
            table = document.getElementById("event_table");
            tr = table.getElementsByTagName("tr");

            for (j = 0; j < tr.length; j++) {
                td = tr[j].getElementsByTagName("td");
                message = document.getElementById("no_data");

                if (td.length > 0) {
                    if (td[0].innerHTML.toLocaleUpperCase().indexOf(filter) > -1 ||
                        td[1].innerHTML.toLocaleUpperCase().indexOf(filter) > -1 ||
                        td[2].innerHTML.toLocaleUpperCase().indexOf(filter) > -1 ||
                        td[3].innerHTML.toLocaleUpperCase().indexOf(filter) > -1) {
                        tr[j].style.display = "";
                        message.innerHTML = "";
                    }
                    else {
                        tr[j].style.display = "none";
                    }

                }
                if (td.length == 0) {
                    message.innerHTML = "Event not found!";
                }
            }
        }
    </script>
</body>

</html>

public_relation_team/templates/public_relation_team/event/super_event_creation_form.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Branch-Super Event Creation Form- Part-1</title>
    <link rel="stylesheet" href="{% static 'event_form.css' %}">
</head>

<body>
    <div class="event_form">
        <div class="title">
            Super Event Creation Form
        </div>
        <div class="form">
            <form method="POST" action = "{% url 'public_relation_team:super_event_creation' %}">
                {% csrf_token %}
                <div class="inputfield">
                    <label>Name:</label>
                    <input type="text" name="super_event_name" class="input">
                </div>
                <div class="inputfield">
                    <label>Description</label>
                    <textarea type="text" name="super_event_description" placeholder="Write with in 500 words"
                        class="textarea"></textarea>
                </div>
                <div class="inputfield">
                    <label for="">Add a Probable Date For the Event</label>
                    <input type="date" name="probable_date" class="input">
                </div>
                <div class="inputfield">
                    <label for="">Add Final Date For the Event (If finalised)</label>
                    <input type="date" name="final_date" class="input">
                </div>
                <div class="inputfield btn">
                    <input type="submit" name="cancel" value="Cancel" class="btn">
                    <input type="submit" value="Submit" name="Submit" class="btn">
                </div>
            </form>
        </div>
        {% for message in messages %}
        <p>{{message}}</p>
        {% endfor %}
    </div>
</body>

</html>