api/urls.py
import imp
from django.urls import path,include
from api import views

app_name='api'

##defining the urls to work with

urlpatterns = [
    #path('members/',views.MemberList.as_view()),
    path('signup/',views.signupAppUser),
    path('login/',views.loginUser),
    
]

graphics_team/urls.py
from django.urls import path,include
from . import views
from central_branch.views import task_edit,add_task,create_task,upload_task,task_home,forward_to_incharges

app_name="graphics_team"

urlpatterns = [
    path('',views.team_homepage,name="team_homepage"),
    #Manage Team
    path('manage_team/',views.manage_team,name="manage_team"),
    #Event page
    path('event_page/',views.event_page,name="event_page"),
    #Event form
    path('event_page/<int:event_id>',views.event_form,name="event_form"),
    path('event_page/<int:event_id>/add_links',views.event_form_add_links,name="add_link_event_form"),
    path('graphics_drive_links/',views.graphics_drive_links,name="graphics_drive_links"),

    #Task
    path('create_task/<int:team_primary>/',create_task,name="create_task_team"),
    path('task_home/<int:team_primary>/',task_home,name="task_home_team"),
    path('task/<int:task_id>/<int:team_primary>/',task_edit,name="task_edit_team"),
    path('task/<int:task_id>/upload_task/<int:team_primary>/',upload_task,name="upload_task_team"),
    path('task/<int:task_id>/forward_to_incharges/<int:team_primary>/',forward_to_incharges,name="forward_to_incharges"),
    path('task/<int:task_id>/add_task/<int:team_primary>/<int:by_coordinators>/',add_task,name="add_task_team"),

]

insb_port/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    
    path('',include('main_website.urls',namespace='main_website')),
    path('portal/',include('port.urls',namespace='port')),
    path('api/',include('api.urls')),
    path('admin/', admin.site.urls),
    path('system/',include('system_administration.urls',namespace="system")),
    path('portal/users/',include('users.urls',namespace="users")),
    path('portal/notifications/',include('notification.urls',namespace="notification")),
    path('portal/recruitment/',include('recruitment.urls',namespace="recruitment")),
    path('portal/central_branch/',include('central_branch.urls',namespace='central_branch')),
    path('portal/membership_development_team/',include('membership_development_team.urls',namespace='membership_development_team')),
    path('portal/public_relation_team/',include('public_relation_team.urls',namespace='public_relation_team')),
    path('portal/system_administration',include('system_administration.urls',namespace='system_administration')),
    path('portal/events_and_management_team/',include('events_and_management_team.urls',namespace="events_and_management_team")),
    path('portal/logistics_and_operations_team/',include('logistics_and_operations_team.urls',namespace="logistics_and_operations_team")),
    path('portal/content_writing_and_publications_team/',include('content_writing_and_publications_team.urls',namespace="content_writing_and_publications_team")),
    path('portal/promotions_team/',include('promotions_team.urls',namespace="promotions_team")),
    path('portal/website_development_team/',include('website_development_team.urls',namespace='website_development_team')),
    path('portal/media_team/',include('media_team.urls',namespace='media_team')),
    path('portal/graphics_team/',include('graphics_team.urls',namespace="graphics_team")),
    path('portal/finance_and_corporate_team/',include("finance_and_corporate_team.urls",namespace="finanace_and_corporate_team")),
    path('portal/SC_AG/',include("chapters_and_affinity_group.urls",namespace="sc_ag")),
    re_path(r'^media_files/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}), 
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
]
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# handler404 = 'main_website.views.custom_404'

users/urls.py
from django.urls import path,include
from django.contrib.auth.views import LogoutView
from . import views
from django.conf import settings
from central_branch.views import upload_task, task_edit


app_name='users'

##defining the urls to work with

urlpatterns = [
    #include default auth urls
    #path('', include('django.contrib.auth.urls')),
    #loginpage
    path('login',views.login, name='login'),
    # signup user validation
    path('signup/validation/',views.signup_user_validation,name="signup_validation"),
    #signup page
    path('signup/<int:ieee_id>/<str:token>/',views.signup,name='signup'),
    #dashboard
    path('dashboard',views.dashboard,name='dashboard'),
    #logoutUser
    path('logout/',views.logoutUser,name='logoutUser'),
    #user Profile
    path('profile',views.profile_page,name='profile'),
    #user Profile settings
    path('change_password',views.change_password,name='change_password'),
    #user Profile update information
    path('update_information',views.update_information,name='update_information'),
    #forgot password
    path('username_validation',views.forgotPassword_getUsername,name="fp_validation"), #fp=forgot password, this page just checks if the username is registered or not
    #forgot password
    path('reset_password/<str:username>/<str:token>/',views.forgotPassword_resetPassword,name="reset_password"),
    #Invalid URL Handling
    path('invalid_url',views.invalidURL,name="invalid_url"), #this page will prompt if an user has used an "used" or invalid url
    #my task url
    path('my_tasks/',views.my_tasks,name="my_tasks"),
    path('my_tasks/<int:task_id>/',task_edit,name="edit_task_user"),
    path('my_tasks/<int:task_id>/upload_tasks/',upload_task,name="upload_task_user"),
 
]

graphics_team/models.py
from django.db import models
from central_events.models import Events
from django_resized import ResizedImageField
from PIL import Image, ExifTags
from io import BytesIO
from django.core.files import File

# Create your models here.
#Table for Media Links and Images
class Graphics_Link(models.Model):
    event_id=models.ForeignKey(Events,on_delete=models.CASCADE)
    graphics_link=models.URLField(null=True,blank=True,max_length=300)
class Graphics_Banner_Image(models.Model):
    event_id=models.ForeignKey(Events,on_delete=models.CASCADE)
    selected_image=ResizedImageField(null=True,blank=True,default=None,upload_to='Event_Banner_Image/')

class Graphics_Form_Link(models.Model):
    event_id = models.ForeignKey(Events,on_delete=models.CASCADE)
    graphics_form_link_name = models.CharField(null=True,blank=True,max_length = 200)
    graphics_form_link = models.URLField(null=True,blank=True,max_length=300)
class Graphics_Drive_links(models.Model):

    link_title = models.TextField(null=True,blank=True,default="")
    link = models.URLField(blank=True,null=True,default="www.google_drive_link.com")
    created_at = models.DateTimeField(auto_now_add = True)

    class Meta:

        verbose_name = "Graphics_Drive_link" 
        ordering = ['-created_at']

graphics_team/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from graphics_team.manage_access import GraphicsTeam_Render_Access
from system_administration.render_access import Access_Render
from users.models import Members
from central_branch.renderData import Branch
from port.models import Roles_and_Position
from django.contrib import messages
from system_administration.models import Graphics_Data_Access
from .renderData import GraphicsTeam
from users.renderData import LoggedinUser
from . import renderData
from django.conf import settings
from central_events.models import Events
from .models import Graphics_Banner_Image,Graphics_Link,Graphics_Drive_links
import traceback
import logging
from system_administration.system_error_handling import ErrorHandling
from django.http import Http404,HttpResponseBadRequest
from datetime import datetime
from port.renderData import PortData
from users.renderData import PanelMembersData,member_login_permission
from users import renderData
from central_branch import views as cv

logger=logging.getLogger(__name__)
# Create your views here.
@login_required
@member_login_permission
def team_homepage(request):

    try:

        sc_ag=PortData.get_all_sc_ag(request=request)
        current_user=LoggedinUser(request.user) #Creating an Object of logged in user with current users credentials
        user_data=current_user.getUserData() #getting user data as dictionary file
        
        get_team_members=GraphicsTeam.get_team_members_with_positions()
        context={
            'all_sc_ag':sc_ag,
            'co_ordinators':get_team_members[0],
            'incharges':get_team_members[1],
            'media_url':settings.MEDIA_URL,
            'user_data':user_data,
            'core_volunteers':get_team_members[2],
            'team_volunteers':get_team_members[3],
        }


        return render(request,"Homepage/graphics_homepage.html",context)
    
    except Exception as e:
        logger.error("An error occurred at {datetime}".format(datetime=datetime.now()), exc_info=True)
        ErrorHandling.saveSystemErrors(error_name=e,error_traceback=traceback.format_exc())
        return cv.custom_500(request)

@login_required
@member_login_permission
def manage_team(request):

    try:

        current_user=renderData.LoggedinUser(request.user) #Creating an Object of logged in user with current users credentials
        user_data=current_user.getUserData() #getting user data as dictionary file
        '''This function loads the manage team page for graphics team and is accessable
        by the co-ordinatiors and other admin users only, unless the co-ordinators gives access to others as well'''
        
        sc_ag=PortData.get_all_sc_ag(request=request)
        has_access = GraphicsTeam_Render_Access.access_for_manage_team(request)
        if has_access:
            data_access = GraphicsTeam.load_data_access()
            team_members = GraphicsTeam.load_team_members()
            #load all position for insb members
            position=PortData.get_all_volunteer_position_with_sc_ag_id(request=request,sc_ag_primary=1)
                    
            #load all insb members
            all_insb_members=Members.objects.all()
            #load all current panel members
            current_panel_members = Branch.load_current_panel_members()

            if request.method == "POST":
                if (request.POST.get('add_member_to_team')):
                    #get selected members
                    members_to_add=request.POST.getlist('member_select1')
                    #get position
                    position=request.POST.get('position')
                    for member in members_to_add:
                        GraphicsTeam.add_member_to_team(member,position)
                    messages.success(request,"Added new Members to the Team!")
                    return redirect('graphics_team:manage_team')
                
                if (request.POST.get('remove_member')):
                    '''To remove member from team table'''
                    try:
                        load_current_panel=Branch.load_current_panel()
                        PanelMembersData.remove_member_from_panel(ieee_id=request.POST['remove_ieee_id'],panel_id=load_current_panel.pk,request=request)
                        try:
                            Graphics_Data_Access.objects.filter(ieee_id=request.POST['remove_ieee_id']).delete()
                        except Graphics_Data_Access.DoesNotExist:
                            return redirect('graphics_team:manage_team')
                        return redirect('graphics_team:manage_team')
                    except:
                        pass

                if request.POST.get('access_update'):
                    manage_team_access = False
                    if(request.POST.get('manage_team_access')):
                        manage_team_access=True
                    event_access=False
                    if(request.POST.get('event_access')):
                        event_access=True
                    graphics_access=False
                    if(request.POST.get('graphics_access')):
                        graphics_access=True
                    graphics_view_access=False
                    if(request.POST.get('graphics_view_access')):
                        graphics_view_access=True
                    ieee_id=request.POST['access_ieee_id']
                    if (GraphicsTeam.graphics_manage_team_access_modifications(manage_team_access, event_access, graphics_access, graphics_view_access, ieee_id)):
                        permission_updated_for=Members.objects.get(ieee_id=ieee_id)
                        messages.info(request,f"Permission Details Was Updated for {permission_updated_for.name}")
                    else:
                        messages.info(request,f"Something Went Wrong! Please Contact System Administrator about this issue")

                if request.POST.get('access_remove'):
                    '''To remove record from data access table'''
                    
                    ieeeId=request.POST['access_ieee_id']
                    if(GraphicsTeam.remove_member_from_manage_team_access(ieee_id=ieeeId)):
                        messages.info(request,"Removed member from Managing Team")
                        return redirect('graphics_team:manage_team')
                    else:
                        messages.info(request,"Something went wrong!")

                if request.POST.get('update_data_access_member'):
                    
                    new_data_access_member_list=request.POST.getlist('member_select')
                    
                    if(len(new_data_access_member_list)>0):
                        for ieeeID in new_data_access_member_list:
                            if(GraphicsTeam.add_member_to_manage_team_access(ieeeID)=="exists"):
                                messages.info(request,f"The member with IEEE Id: {ieeeID} already exists in the Data Access Table")
                            elif(GraphicsTeam.add_member_to_manage_team_access(ieeeID)==False):
                                messages.info(request,"Something Went wrong! Please try again")
                            elif(GraphicsTeam.add_member_to_manage_team_access(ieeeID)==True):
                                messages.info(request,f"Member with {ieeeID} was added to the team table!")
                                return redirect('graphics_team:manage_team')

            context={
                'data_access':data_access,
                'members':team_members,
                'insb_members':all_insb_members,
                'current_panel_members':current_panel_members,
                'positions':position,
                'all_sc_ag':sc_ag,
                'user_data':user_data,
            }  
            return render(request,"graphics_team/manage_team.html",context=context)
        else:
            return render(request,"access_denied2.html", { 'all_sc_ag' : sc_ag ,'user_data':user_data,})
        
    except Exception as e:
        logger.error("An error occurred at {datetime}".format(datetime=datetime.now()), exc_info=True)
        ErrorHandling.saveSystemErrors(error_name=e,error_traceback=traceback.format_exc())
        return cv.custom_500(request)

@login_required
@member_login_permission
def event_page(request):

    try:

        sc_ag=PortData.get_all_sc_ag(request=request)
        current_user=renderData.LoggedinUser(request.user) #Creating an Object of logged in user with current users credentials
        user_data=current_user.getUserData() #getting user data as dictionary file
        '''Only events organised by INSB would be shown on the event page of Graphics Team
        So, only those events are being retrieved from database'''
        insb_organised_events = Branch.load_insb_organised_events()
        sc_ag=PortData.get_all_sc_ag(request=request)
    
        context = {
            'all_sc_ag':sc_ag,
            'events_of_insb_only':insb_organised_events,
            'user_data':user_data,
        }


        return render(request,"Events/graphics_team_events.html",context)
    
    except Exception as e:
        logger.error("An error occurred at {datetime}".format(datetime=datetime.now()), exc_info=True)
        ErrorHandling.saveSystemErrors(error_name=e,error_traceback=traceback.format_exc())
        return cv.custom_500(request)
@login_required
@member_login_permission
def event_form(request,event_id):

    sc_ag=PortData.get_all_sc_ag(request=request)
    current_user=renderData.LoggedinUser(request.user) #Creating an Object of logged in user with current users credentials
    user_data=current_user.getUserData() #getting user data as dictionary file
    #Initially loading the events whose  links and images were previously uploaded
    #and can be editible

    try:
        sc_ag=PortData.get_all_sc_ag(request=request)

graphics_team/templates/graphics_navbar.html
{% load static %}
{% block navbar %}
<style>
    .nav a.active {
        color: #FFA300;
    }
    .app-header{
        position: sticky;
        margin: 0 0 0 2px;
    }
    .app-header ~ .app-body {
        padding-top: 0rem;
    }
</style>
<!--This is scrip is to get the link of the current page and cross match it with the navlink to change colors-->
<script>
document.addEventListener("DOMContentLoaded", function () {
    // Get the current page's URL
    const currentPageUrl = window.location.href;
  
    // Find the links in the navigation bar
    const navLinks = document.querySelectorAll(".nav a");
  
    // Loop through the links and add a "active" class to the matching link
    navLinks.forEach(function (link) {
      if (link.href === currentPageUrl) {
        link.classList.add("active");
      }
    });
  });
</script>
<div class="app-header white box-shadow">
    <div class="navbar navbar-toggleable-sm flex-row align-items-center">
        <!-- Open side - Naviation on mobile -->
        <a data-toggle="modal" data-target="#aside" class="hidden-lg-up mr-3">
        <i class="material-icons">&#xe5d2;</i>
        </a>
        <!-- / -->
    
        <!-- Page title - Bind to $state's title -->
        <div class="mb-0 h5 no-wrap" ng-bind="$state.current.data.title" id="pageTitle"></div>
    
        <!-- navbar collapse -->
        <div class="collapse navbar-collapse" id="collapse">
        <!-- link and dropdown -->
        <ul class="nav navbar-nav mr-auto">
            <li class="nav-item dropdown">
                <a class="nav-link" href="{% url 'graphics_team:team_homepage' %}">
                <i class="fa fa-home"></i>
                <span>Home</span>
                </a>
                <div ui-include="'../views/blocks/dropdown.new.html'"></div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link" href="{% url 'graphics_team:event_page' %}">
                <i class="fa fa-calendar"></i>
                <span>Events</span>
                </a>
                <div ui-include="'../views/blocks/dropdown.new.html'"></div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link" href="{% url 'graphics_team:task_home_team' 10 %}">
                <i class="fa fa-tasks" aria-hidden="true"></i>
                <span>Task</span>
                </a>
                <div ui-include="'../views/blocks/dropdown.new.html'"></div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link" href="{% url 'graphics_team:graphics_drive_links' %}"> 
                <i class="fa fa-pencil" aria-hidden="true"></i>
                <span>Graphics</span>
                </a>
                <div ui-include="'../views/blocks/dropdown.new.html'"></div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link" href="{% url 'graphics_team:manage_team' %}">
                <i class="fa fa-calendar"></i>
                <span>Manage Team</span>
                </a>
                <div ui-include="'../views/blocks/dropdown.new.html'"></div>
            </li>
        </ul>
    
        <div ui-include="'../views/blocks/navbar.form.html'"></div>
        <!-- / -->
        </div>
        <!-- / navbar collapse -->
    
        <!-- / navbar right -->
    <ul class="nav navbar-nav ml-auto flex-row">
        <li class="nav-item hidden-md-up">
            <a class="nav-link pl-2" data-toggle="collapse" data-target="#collapse">
            <i class="material-icons">more_horiz</i>
            </a>
        </li>
        <!--notification bell-->
        {% block bell_notification %}
            {% include 'users/bell_notification.html' %}
        {% endblock bell_notification %}
        <li class="nav-item dropdown">
            <a class="nav-link p-0 clear" href="{% url 'users:profile' %}">
            <span class="avatar w-32" style="border-radius: 50%;
            overflow: hidden;">
                <img src="{{ user_data.profile_picture }}" alt="user_profile" style="border-radius: 0;
                width: 100%;
                height: 100%;
                object-fit: cover;">
                <i class="on b-white bottom"></i>
            </span>
            </a>
            <div ui-include="'../views/blocks/dropdown.user.html'"></div>
        </li>
        </ul>
    <!-- / navbar right -->
  </div>
{% endblock navbar %}